import { useEffect, useState } from 'react'
import { getTemplates, createTemplate, activateTemplate, deleteTemplate } from '../../api/templates.api'
import { notify as toast } from '../../lib/notify'
import { getPrograms } from '../../api/programs.api'

const XIcon = () => (
  <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
  </svg>
)
const EditIcon = () => (
  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/>
  </svg>
)

const TrashIcon = () => (
  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/>
  </svg>
)

const DEFAULT_PLACEHOLDERS = ['NumriRendor', 'Data', 'KodiProgramit', 'EmriTrajnimit', 'EmriDheMbiemri']

const EMPTY_FORM = {
  name: '', description: '', certificationType: '', location: 'Prishtinë',
  trainingProgramId: '', placeholders: [...DEFAULT_PLACEHOLDERS], file: null,
  logo1: null, logo2: null, logo3: null,
  signature1: null, signature1Name: '',
  signature2: null, signature2Name: '',
  signature3: null, signature3Name: '',
}

export default function TemplatesPage() {
  const [templates, setTemplates] = useState([])
  const [programs, setPrograms] = useState([])
  const [totalCount, setTotalCount] = useState(0)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [pageNumber, setPageNumber] = useState(1)
  const pageSize = 10

  const [showUpload, setShowUpload] = useState(false)
  const [form, setForm] = useState(EMPTY_FORM)
  const [newPlaceholder, setNewPlaceholder] = useState('')
  const [formError, setFormError] = useState('')
  const [saving, setSaving] = useState(false)

  const [activateModal, setActivateModal] = useState(null)
  const [activateProgramId, setActivateProgramId] = useState('')
  const [activating, setActivating] = useState(false)

  const [deleteModal, setDeleteModal] = useState(null)
  const [deleting, setDeleting] = useState(false)

  const load = () => {
    setLoading(true)
    getTemplates({ pageNumber, pageSize })
      .then(({ data }) => { setTemplates(data.items || []); setTotalCount(data.totalCount || 0) })
      .catch(() => setError('Ngarkimi i shablloneve dështoi.'))
      .finally(() => setLoading(false))
  }

  useEffect(() => { load() }, [pageNumber])
  useEffect(() => {
    getPrograms({ pageSize: 100 }).then(({ data }) => setPrograms(data.items || [])).catch(() => {})
  }, [])

  const handleUpload = async (e) => {
    e.preventDefault()
    // File is optional - PDF is auto-generated by system
    setFormError(''); setSaving(true)
    try {
      await createTemplate(form)
      setShowUpload(false); setForm(EMPTY_FORM); load()
      toast.success('Shablloni u krijua me sukses!')
    } catch (err) {
      setFormError(err.response?.data?.detail || 'Ngarkimi dështoi.')
    } finally { setSaving(false) }
  }

  const handleActivate = async (e) => {
    e.preventDefault()
    if (!activateProgramId) return
    setActivating(true)
    try { await activateTemplate(activateModal.id, activateProgramId); setActivateModal(null); load(); toast.success('Shablloni u aktivizua!') }
    catch { toast.error('Aktivizimi dështoi.') }
    finally { setActivating(false) }
  }

  const handleDelete = async () => {
    setDeleting(true)
    try {
      await deleteTemplate(deleteModal.id)
      setDeleteModal(null)
      load()
      toast.success('Shablloni u fshi me sukses!')
    } catch { toast.error('Fshirja dështoi.') }
    finally { setDeleting(false) }
  }

  const set = (key, val) => setForm(f => ({ ...f, [key]: val }))
  const addPlaceholder = () => {
    const val = newPlaceholder.trim()
    if (!val || form.placeholders.includes(val)) return
    set('placeholders', [...form.placeholders, val]); setNewPlaceholder('')
  }

  const totalPages = Math.ceil(totalCount / pageSize)

  return (
    <div className="space-y-4">
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-2xl font-black text-slate-800">Shablllonet e Certifikatave</h1>
          <p className="text-sm text-slate-400 mt-1">Menaxhoni formatet, logot, nënshkrimet dhe fushat dinamike</p>
        </div>
        <button onClick={() => { setShowUpload(true); setFormError('') }}
          className="flex items-center gap-2 px-5 py-3 bg-slate-800 hover:bg-slate-700 text-white rounded-xl font-bold text-sm transition-all">
          + Shto Shabllon
        </button>
      </div>

      {error && <div className="px-4 py-3 bg-red-50 text-red-600 text-sm rounded-xl">{error}</div>}

      {/* Table view */}
      <div className="bg-white rounded-2xl border border-slate-100 shadow-sm overflow-hidden">
        <table className="w-full text-left">
          <thead>
            <tr className="border-b border-slate-100">
              {['Emri', 'Lloji', 'Programi', 'Logo', 'Nënshkrime', 'Vendi', 'Aktiv', 'Veprime'].map(h => (
                <th key={h} className="px-5 py-4 text-[10px] font-black text-slate-400 uppercase tracking-widest">{h}</th>
              ))}
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-50">
            {loading ? (
              <tr><td colSpan={8} className="px-6 py-12 text-center text-sm text-slate-400">Duke ngarkuar...</td></tr>
            ) : templates.length === 0 ? (
              <tr><td colSpan={8} className="px-6 py-12 text-center text-sm text-slate-400">Nuk u gjetën shabllone.</td></tr>
            ) : templates.map(t => {
              const logoCount = [t.logo1FileKey, t.logo2FileKey, t.logo3FileKey].filter(Boolean).length
              const sigCount = [t.signature1FileKey, t.signature2FileKey, t.signature3FileKey].filter(Boolean).length
              const sigNames = [t.signature1Name, t.signature2Name, t.signature3Name].filter(Boolean)
              return (
                <tr key={t.id} className="hover:bg-slate-50/80 transition">
                  <td className="px-5 py-4">
                    <p className="font-bold text-slate-800 text-sm">{t.name}</p>
                    {t.description && <p className="text-[11px] text-slate-400 mt-0.5">{t.description}</p>}
                  </td>
                  <td className="px-5 py-4 text-xs text-slate-600">{t.certificationType || '—'}</td>
                  <td className="px-5 py-4">
                    {t.trainingProgramCode ? (
                      <span className="font-mono text-xs font-bold text-[#00a0e3] bg-blue-50 px-2 py-0.5 rounded">{t.trainingProgramCode}</span>
                    ) : '—'}
                  </td>
                  <td className="px-5 py-4 text-xs text-slate-500">{logoCount}/3</td>
                  <td className="px-5 py-4">
                    <span className="text-xs text-slate-500">{sigCount}/3</span>
                    {sigNames.length > 0 && (
                      <p className="text-[10px] text-slate-400 mt-0.5">{sigNames.join(', ')}</p>
                    )}
                  </td>
                  <td className="px-5 py-4 text-xs text-slate-500">{t.location}</td>
                  <td className="px-5 py-4">
                    <span className={`px-2 py-0.5 rounded-full text-[10px] font-bold uppercase ${t.isActive ? 'bg-green-50 text-green-600' : 'bg-slate-100 text-slate-400'}`}>
                      {t.isActive ? 'Aktiv' : 'Jo'}
                    </span>
                  </td>
                  <td className="px-5 py-4">
                    <div className="flex items-center gap-2">
                      <button onClick={() => { setActivateModal(t); setActivateProgramId('') }}
                        className="w-8 h-8 rounded-lg bg-slate-50 text-slate-400 hover:bg-blue-50 hover:text-[#00a0e3] transition-all flex items-center justify-center" title="Aktivizo">
                        <EditIcon />
                      </button>
                      <button onClick={() => setDeleteModal(t)}
                        className="w-8 h-8 rounded-lg bg-slate-50 text-slate-400 hover:bg-red-50 hover:text-red-500 transition-all flex items-center justify-center" title="Fshi">
                        <TrashIcon />
                      </button>
                    </div>
                  </td>
                </tr>
              )
            })}
          </tbody>
        </table>
        {totalPages > 1 && (
          <div className="flex items-center justify-between px-6 py-4 border-t border-slate-100">
            <span className="text-sm text-slate-400">{totalCount} shabllone gjithsej</span>
            <div className="flex items-center gap-2">
              <button disabled={pageNumber === 1} onClick={() => setPageNumber(p => p - 1)}
                className="px-4 py-2 border border-slate-200 rounded-xl text-sm font-medium hover:bg-slate-50 disabled:opacity-40">← Para</button>
              <span className="text-sm text-slate-500 px-2">{pageNumber} / {totalPages}</span>
              <button disabled={pageNumber === totalPages} onClick={() => setPageNumber(p => p + 1)}
                className="px-4 py-2 border border-slate-200 rounded-xl text-sm font-medium hover:bg-slate-50 disabled:opacity-40">Pas →</button>
            </div>
          </div>
        )}
      </div>

      {/* Upload Modal */}
      {showUpload && (
        <div className="fixed inset-0 bg-black/70 flex items-center justify-center z-50 p-4" onClick={() => setShowUpload(false)}>
          <div className="bg-white rounded-2xl shadow-2xl w-full max-w-2xl p-8 max-h-[90vh] overflow-y-auto" onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-lg font-black text-slate-800">Shto Shabllon të Ri</h2>
              <button onClick={() => setShowUpload(false)} className="w-8 h-8 rounded-lg bg-slate-50 text-slate-400 hover:bg-slate-100 flex items-center justify-center"><XIcon /></button>
            </div>

            <form onSubmit={handleUpload} className="space-y-5">
              {/* Basic info */}
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-bold text-slate-400 uppercase tracking-wider mb-1">Emërtimi *</label>
                  <input required value={form.name} onChange={e => set('name', e.target.value)}
                    className="w-full p-3 bg-slate-50 border border-slate-200 rounded-xl outline-none focus:border-[#00a0e3] text-sm" />
                </div>
                <div>
                  <label className="block text-xs font-bold text-slate-400 uppercase tracking-wider mb-1">Lloji i Certifikimit</label>
                  <input value={form.certificationType} onChange={e => set('certificationType', e.target.value)}
                    placeholder="p.sh. Certifikatë Pjesëmarrjeje"
                    className="w-full p-3 bg-slate-50 border border-slate-200 rounded-xl outline-none focus:border-[#00a0e3] text-sm" />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-bold text-slate-400 uppercase tracking-wider mb-1">Programi</label>
                  <select value={form.trainingProgramId} onChange={e => set('trainingProgramId', e.target.value)}
                    className="w-full p-3 bg-slate-50 border border-slate-200 rounded-xl outline-none focus:border-[#00a0e3] text-sm">
                    <option value="">Asnjë</option>
                    {programs.map(p => <option key={p.id} value={p.id}>{p.code} — {p.name}</option>)}
                  </select>
                </div>
                <div>
                  <label className="block text-xs font-bold text-slate-400 uppercase tracking-wider mb-1">Vendi</label>
                  <input value={form.location} onChange={e => set('location', e.target.value)}
                    className="w-full p-3 bg-slate-50 border border-slate-200 rounded-xl outline-none focus:border-[#00a0e3] text-sm" />
                </div>
              </div>

              {/* Template file - hidden, auto-generated by system */}

              {/* Logos */}
              <div>
                <label className="block text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">Logot (deri në 3)</label>
                <div className="grid grid-cols-3 gap-3">
                  {[1, 2, 3].map(n => (
                    <div key={n}>
                      <label className="block text-[10px] text-slate-400 mb-1">Logo {n}</label>
                      <input type="file" accept="image/*" onChange={e => set(`logo${n}`, e.target.files[0])}
                        className="w-full text-xs text-slate-500 file:mr-2 file:py-1 file:px-3 file:rounded-lg file:border-0 file:text-xs file:bg-slate-100 file:text-slate-600" />
                    </div>
                  ))}
                </div>
              </div>

              {/* Signatures */}
              <div>
                <label className="block text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">Nënshkrimet (deri në 3)</label>
                <div className="space-y-3">
                  {[1, 2, 3].map(n => (
                    <div key={n} className="grid grid-cols-2 gap-3 p-3 bg-slate-50 rounded-xl">
                      <div>
                        <label className="block text-[10px] text-slate-400 mb-1">Nënshkrim {n} (imazh)</label>
                        <input type="file" accept="image/*" onChange={e => set(`signature${n}`, e.target.files[0])}
                          className="w-full text-xs text-slate-500 file:mr-2 file:py-1 file:px-3 file:rounded-lg file:border-0 file:text-xs file:bg-white file:text-slate-600" />
                      </div>
                      <div>
                        <label className="block text-[10px] text-slate-400 mb-1">Emri i nënshkruesit</label>
                        <input value={form[`signature${n}Name`]} onChange={e => set(`signature${n}Name`, e.target.value)}
                          placeholder="Emri dhe mbiemri"
                          className="w-full p-2 bg-white border border-slate-200 rounded-lg outline-none focus:border-[#00a0e3] text-xs" />
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Description */}
              <div>
                <label className="block text-xs font-bold text-slate-400 uppercase tracking-wider mb-1">Përshkrimi</label>
                <textarea rows={2} value={form.description} onChange={e => set('description', e.target.value)}
                  className="w-full p-3 bg-slate-50 border border-slate-200 rounded-xl outline-none focus:border-[#00a0e3] text-sm resize-none" />
              </div>

              {formError && <p className="text-red-600 bg-red-50 px-4 py-3 rounded-xl text-sm">{formError}</p>}

              <div className="flex justify-end gap-3 pt-2">
                <button type="button" onClick={() => setShowUpload(false)}
                  className="px-5 py-2.5 border border-slate-200 rounded-xl text-sm font-semibold text-slate-600 hover:bg-slate-50">Anulo</button>
                <button type="submit" disabled={saving}
                  className="px-5 py-2.5 bg-slate-800 hover:bg-slate-700 text-white rounded-xl text-sm font-bold disabled:opacity-70">
                  {saving ? 'Duke ngarkuar...' : 'Ruaj Shabllonin'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Delete Modal */}
      {deleteModal && (
        <div className="fixed inset-0 bg-black/70 flex items-center justify-center z-50 p-4" onClick={() => setDeleteModal(null)}>
          <div className="bg-white rounded-2xl shadow-2xl w-full max-w-md p-8" onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-lg font-black text-slate-800">Fshi Shabllonin</h2>
              <button onClick={() => setDeleteModal(null)} className="w-8 h-8 rounded-lg bg-slate-50 text-slate-400 hover:bg-slate-100 flex items-center justify-center"><XIcon /></button>
            </div>
            <p className="text-sm text-slate-600 mb-6">
              Jeni të sigurt që dëshironi të fshini shabllonin <strong>{deleteModal.name}</strong>? Ky veprim nuk mund të kthehet.
            </p>
            <div className="flex justify-end gap-3">
              <button onClick={() => setDeleteModal(null)}
                className="px-5 py-2.5 border border-slate-200 rounded-xl text-sm font-semibold text-slate-600 hover:bg-slate-50">Anulo</button>
              <button onClick={handleDelete} disabled={deleting}
                className="px-5 py-2.5 bg-red-500 hover:bg-red-600 text-white rounded-xl text-sm font-bold disabled:opacity-70">
                {deleting ? 'Duke fshirë...' : 'Fshi'}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Activate Modal */}
      {activateModal && (
        <div className="fixed inset-0 bg-black/70 flex items-center justify-center z-50 p-4" onClick={() => setActivateModal(null)}>
          <div className="bg-white rounded-2xl shadow-2xl w-full max-w-sm p-8" onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-lg font-black text-slate-800">Aktivizo Shabllonin</h2>
              <button onClick={() => setActivateModal(null)} className="w-8 h-8 rounded-lg bg-slate-50 text-slate-400 hover:bg-slate-100 flex items-center justify-center"><XIcon /></button>
            </div>
            <p className="text-sm text-slate-500 mb-5">
              Aktivizo <span className="font-bold text-slate-700">{activateModal.name}</span> për programin:
            </p>
            <form onSubmit={handleActivate} className="space-y-4">
              <select required value={activateProgramId} onChange={e => setActivateProgramId(e.target.value)}
                className="w-full p-3 bg-slate-50 border border-slate-200 rounded-xl outline-none focus:border-[#00a0e3] text-sm">
                <option value="">Zgjidh programin...</option>
                {programs.map(p => <option key={p.id} value={p.id}>{p.code} — {p.name}</option>)}
              </select>
              <div className="flex justify-end gap-3">
                <button type="button" onClick={() => setActivateModal(null)}
                  className="px-5 py-2.5 border border-slate-200 rounded-xl text-sm font-semibold text-slate-600 hover:bg-slate-50">Anulo</button>
                <button type="submit" disabled={activating}
                  className="px-5 py-2.5 bg-[#00a0e3] hover:bg-[#008cc7] text-white rounded-xl text-sm font-bold disabled:opacity-70">
                  {activating ? 'Duke aktivizuar...' : 'Aktivizo'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  )
}
